language: ruby

addons:
  ssh_known_hosts: 95.216.174.30

script:
  ruby t.rb

before_deploy:
- openssl aes-256-cbc -K $encrypted_67893bd5f42b_key -iv $encrypted_67893bd5f42b_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  skip_cleanup: true
